
services:
  authentication:
    build:
      context: ./authentication
    container_name: authentication_service
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - USER_ID=${USER_ID}               
      - USER_PASSWORD=${USER_PASSWORD}    
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./authentication:/app
    networks:
      - expense_network

  enter_data_backend:
    build:
      context: ./enter_data/backend
    container_name: enter_data_service
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./enter_data/backend:/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - expense_network

  enter_data_frontend:
    image: nginx:alpine
    container_name: enter_data_frontend
    volumes:
      - ./enter_data/frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - expense_network

  mysql:
    image: swimminwebdev/expense-mysql-server:latest
    container_name: expense-mysql-server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - expense_network
    healthcheck:   # Healthcheck configuration
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  analytics:
    build:
      context: ./analytics
    container_name: analytics_service
    ports:
      - "5003:5003"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./analytics:/app
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - expense_network


  mongodb:
    image: swimminwebdev/expense-mongo-server:latest
    container_name: expense-mongo-server
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: analytics_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - expense_network
    healthcheck:    # Healthcheck configuration
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  show_results_backend:
    build:
      context: ./show_results/backend
    container_name: show_results_service
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./show_results/backend:/app
      - /app/node_modules # avoid overriding node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - expense_network

  show_results_frontend:
    image: nginx:alpine
    container_name: show_results_frontend
    volumes:
      - ./show_results/frontend:/usr/share/nginx/html
    ports:
      - "8081:80"
    networks:
      - expense_network

volumes:
  mysql_data:
  mongodb_data:

networks:
  expense_network:
    driver: bridge
